version: '3.3'

services:
  db:
    image: mariadb
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME:-wordpress}
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6.0.1
    ports:
      - '8000:80'
    volumes:
      - ./.htaccess:/var/www/html/.htaccess
      - ./wp-content:/var/www/html/wp-content
      - ./wp-content/themes/timber/assets/vendor:/var/www/html/wp-content/themes/timber/assets/vendor
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: somewordpress
      WORDPRESS_DB_NAME: ${COMPOSE_PROJECT_NAME:-wordpress}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ENV', 'development');
        define('WP_LOCAL_DEV', true);
        define('WP_THEME', 'timber');
volumes:
  db_data: {}
