#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com
# https://gist.github.com/sindresorhus/7996717

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
    echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# `npm install` if package.json changed
check_run package.json "npm install"

# `bower install` if bower.json changed
check_run bower.json "bower install"

# `composer install` if composer.lock changed
check_run composer.lock "composer install"

# re-run chmod on  ACF to ensure files are editable
chmod 755 -R wp-content/themes/timber/acf-json/*
